sudo: false
language: node_js

node_js:
  - 10

cache:
  directories:
    - $(npm config get prefix)/usr/lerna
    - $(npm config get prefix)/lib/node_modules
    - ui-core/node_modules

before_install:
  - npm install -g lerna

install:
  - lerna bootstrap

before_script:
  - npm install -g codecov

script:
  - lerna run lint
  - lerna run coverage

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc
  - lerna run docz:build

deploy:
  - provider: script
    script: "npm run publish-all"
    skip_cleanup: true
    on:
      node: "10"
      tags: true

  - provider: pages
    github-token: "$GITHUB_TOKEN"
    skip-cleanup: true
    local-dir: "packages/ui-core/docs"
    keep-history: true
    on:
      branch: master
      node_js: "10"

after_script:
  - codecov
