sudo: false
language: node_js

node_js:
  - 8
  - 10

cache:
  directories:
  - node_modules

before_script:
  - npm install -g codecov
  - npm install

script:
  - npm run lint
  - npm run coverage

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      npm run docz:build
    fi

deploy:
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      node_js: "8"

  - provider: pages
    github-token: "$GITHUB_TOKEN"
    skip-cleanup: true
    local-dir: "docs"
    keep-history: true
    on:
      branch: master
      node_js: "8"

after_script:
  - codecov
