sudo: false
language: node_js

node_js:
  - 8
  - 10

cache:
  yarn: true
  directories:
  - node_modules

before_script:
  - npm install -g codecov
  - npm run setup

script:
  - npm run lint
  - npm run coverage

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true

after_script:
  - codecov
