sudo: false
language: node_js

node_js:
  - 8
  - 10

cache:
  yarn: true
  directories:
  - node_modules

before_script:
  - npm install -g codecov
  - npm run setup

script:
  - npm run lint
  - npm run coverage

after_script:
  - codecov
